sudo: false
language: node_js
node_js:
- lts/*
- node
after_success:
- npm run coveralls
before_install:
- npm install -g npm
deploy:
  provider: releases
  api_key:
    secure: n3J/05D1GheYfegPIDS8CaFzcc2g4f1VsRD5EvyqGE+cj2zmRCVvxvWzmXy0e6L+dI8fSNjlFY6JYn07aUn12eXrTWjVO69DM7UO7tnrV6SHEWYTPivSkQ2U8bzRuy/SbkiEK96QqoaGnqqbSwmOehLkLswnLuc2cuQ6Ap2gpHwJNd/MhDCLeLE//99nJNIw5cIcMMUD/UivDMWQHf12iUfMaqNtlsyFYz0+SAuxJQR9pLJ5xpIeXXV/jPl9V+tbRVsxFsUQwqdQ1bfCoMM4lHKjbrfmNc7Ld6RGrIb1OPQ2VvOhjE+4Tk2yJP/0JXtn14WkxOYaWeuGhYjbTIr5RfBtqT8F8TO5aZEIWETEhR+NL+3fwST5+vF/JXlfSDOSTt2PfLUQQJUM9AHFZequctuxJkE43ca5h7STfbaYqr9prx7e6klnKbhky9g01li1KYya4E1N+cu0lQ9hmxtJ7YZsBMys2z6KifmqnZVVyEyIUE58LTVhuENYFP8f2FbNMxfSv6Lk33XyT3KXCKuvDZJMh3GogKctmUDOziOdD4QpMX4IltqGH4QgpmW9QDiyWSO1nuwuSDgUl83ncSq7uMBroG4fC7fR8aDrsILCvy0aOh+XM1Uz++GzQD8djh5/55mmx/mcrPH5TS2CHQ8cxyTE8r9zsPZj8N5L074treA=
  file: dist/grow-theme-user-profile.war
  skip_cleanup: true
  on:
    tags: true
    repo: balcsida/grow-theme-user-profile
