sudo: false
language: node_js
node_js:
- lts/*
- node
after_success:
- npm run coveralls
before_install:
- npm install -g npm
deploy:
  provider: releases
  api_key:
    secure: JDEYcqHPrZ1pfl6eJiJawRU84HFmo1WRYoGThnZ+Faied6LhtludH2fY7J+hNSMtTXaNwzFBW3qYtsPk7tfgGCZtPuD8+z7kBOwD8e+vC4I1tCuQgNvgDXPuYPQK7HErcxdH8Xm/yF/Ks++9stcyRNRKs/oHgbPbJ5NKts4mrDn8AHRL4vwn/fhwvxTsadPF5XnGznOnfK4n4rmi1Ai2301dJ0/XdBMHhbXxvoMQCzp5dZf+WN33Z1k8IJlFgBe8kR6C+BTNcflA9+CIb548WbS4vw/AV6bOKFpSHBKjXh+4n1msDzLx61IdFOB/qAp6LBprU5vUQBjxyX4Eb610nOuBm0GrLMoQkIjNkaB5WTZULp3YA22xMxw3nbmTNXh9mEsZDTzrzmpEkQ2962K0AlTok5ppw2KxSLIo/uV4EZ/hV7kLEL0IIlWJ1+j1FWGkJzK9t1eRmB4u5wHXpLp4jfsx0zSwsmlOSgoHznjU9sIi/EM+EwNUMQlKrC00StzPvHaxGIVZ7mFXboHr0q13lTS9b4WsEbWEadraXrhqzYhz8x1mR5Oo2O8lRsI/7mwcC3Z0jhdVmFM+NTNOnexu5nIUnfLHTC3BDHxpU7o5BprBYdoR20n5wT93uap7G6gDsiBDvLCUP4QRaSqHKpiyCUDCfkEAKxnhm1tkjIo/ylk=
  file: dist/grow-theme-user-profile.war
  on:
    repo: balcsida/grow-theme-user-profile
